### ISSUE TITLE
程序出现连接超时 Connection timed out错误

### ISSUE THREAD

**Issue by JXA-a** [Stars-One/M3u8Downloader#3]
报错信息 如下
java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at com.wan.util.VideoUtil.downloadFile(VideoUtil.kt:281)
	at com.wan.util.VideoUtil.downloadM3u8File(VideoUtil.kt:257)
	at com.wan.util.VideoUtil.<init>(VideoUtil.kt:59)
	at com.wan.view.ItemView$startDownload$1.invoke(ItemView.kt:72)
	at com.wan.view.ItemView$startDownload$1.invoke(ItemView.kt:24)
	at tornadofx.FXTask.call(Async.kt:463)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by stars-one** [comment]
这是连接超时问题，由于网络不好，手动重试应该可以解决问题，后面有空我再实现自动重试功能

**Comment by JXA-a** [comment]
@Stars-One 估计是需要翻墙，程序不支持翻墙？

**Comment by JXA-a** [comment]
java.lang.IllegalArgumentException: Empty key
	at javax.crypto.spec.SecretKeySpec.<init>(SecretKeySpec.java:96)
	at com.wan.util.VideoUtil.<init>(VideoUtil.kt:63)
	at com.wan.view.ItemView$startDownload$1.invoke(ItemView.kt:72)
	at com.wan.view.ItemView$startDownload$1.invoke(ItemView.kt:24)
	at tornadofx.FXTask.call(Async.kt:463)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by stars-one** [comment]
> java.lang.IllegalArgumentException: Empty key
> at javax.crypto.spec.SecretKeySpec.(SecretKeySpec.java:96)
> at com.wan.util.VideoUtil.(VideoUtil.kt:63)
> at com.wan.view.ItemView$startDownload$1.invoke(ItemView.kt:72)
> at com.wan.view.ItemView$startDownload$1.invoke(ItemView.kt:24)
> at tornadofx.FXTask.call(Async.kt:463)
> at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
> at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> at java.lang.Thread.run(Thread.java:748)

软件没有翻墙功能，软件的网络环境和当前的网络环境一样（如果当前是翻墙状态，软件也是翻墙状态）

**Empty Key异常后期修复**

[Issue Empty Key异常](https://github.com/Stars-One/M3u8Downloader/issues/5)

**Comment by JXA-a** [comment]
@Stars-One 是加密的  是没有获取到KEY？ 请见以下M3U8地址

[下载链接](https://d8qtl3txcpjuu.cloudfront.net/8651/video/48407/drmshield/hls/master_8651_48407.m3u8)

**Comment by JXA-a** [comment]
![image](https://user-images.githubusercontent.com/36909175/76386520-a8bb0480-639f-11ea-946c-6e3b6e5efebb.png)
用其他工具下载显示如图

**Comment by stars-one** [comment]
> ![image](https://user-images.githubusercontent.com/36909175/76386520-a8bb0480-639f-11ea-946c-6e3b6e5efebb.png)
> 用其他工具下载显示如图

抱歉，这m3u8的格式我软件并不支持

**Comment by JXA-a** [comment]
不支持？ @Stars-One  软件不就是M3U8的下载工具么？还是说这个链接有啥特殊的？

**Comment by stars-one** [comment]
> 不支持？ @Stars-One 软件不就是M3U8的下载工具么？还是说这个链接有啥特殊的？

那个m3u8的格式和我软件处理的m3u8格式不一样
